### PR TITLE
WIP: add Kerberos role from tower_configuration

### PR DESCRIPTION
**Pull request by ericzolf**
### What does this PR do?

Add the kerberos role removed from tower_configuration collection through redhat-cop/tower_configuration#122 as it fits better in the collection, being close to the operating system and not using the awx.awx collection.

### How should this be tested?

TBD

### Is there a relevant Issue open for this?

relates to redhat-cop/tower_configuration#118

### Other Relevant info, PRs, etc.

* redhat-cop/tower_configuration#122
* #19

### CODE REVIEW

**Comment by ericzolf** [comment]
There was previously a Kerberos role in the collection, so I need to check which one is the best or merge them somehow. I could use a hand from someone who has more knowledge about Kerberos.

**Review by sean-m-sullivan — APPROVED** [review]
Reviewed, it looks good, but I haven't had time to setup a windows domain server + box to test it on.

**Comment by ericzolf** [comment]
I guess, once PR #24 is merged, I can drop this one? And, as already written in the other PR, I'd be keen to learn how you setup (easily) an AD controller (on your laptop?).

**Comment by sean-m-sullivan** [comment]
Once we merge the other one, then we can merge this. I've added a markdown of setup to the other merge.

**Pull request merged**
