### PR TITLE
fix incorrect download bundle

### LINKED ISSUE #199: Incorrect installation setup bundle extracted and configured
# Summary

`infra.aap_utilities.aap_setup_download` downloads 2 different setup types 

1. ansible-automation-platform-containerized-setup-2.4-1.tar.gz
2. ansible-automation-platform-setup-2.4-2.tar.gz

# Issue Type

- Bug Report

# Ansible, Collection, Docker/Podman details

```console (paste below)
ansible --version
ansible [core 2.14.2]
  config file = /root/aap/aap_standalone/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.11/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.11.2 (main, May 24 2023, 00:00:00) [GCC 11.3.1 20221121 (Red Hat 11.3.1-4)] (/usr/bin/python3.11)
  jinja version = 3.1.2
  libyaml = True

ansible-galaxy collection list

# /root/.ansible/collections/ansible_collections
Collection            Version
--------------------- -------
ansible.posix         1.5.4  
awx.awx               23.0.0 
community.crypto      2.15.1 
community.general     7.3.0  
infra.aap_utilities   2.3.0  
kubernetes.core       2.4.0  
nshaik.aap_collection 1.0.14 

podman --version
podman version 4.4.1

```

- ansible installation method: one of source, pip, OS package, EE

# OS / ENVIRONMENT

Ansible Controller installation on RHEL 9.2 version

# Desired Behavior

Installation inventory file should be configured in the correct installation bundle extracted folder

# Actual Behavior

Installation bundle extracted and inventory file is configured in wrong location `/var/tmp/ansible-automation-platform-containerized-setup-2.4-1/` where the correct collection  should be `/var/tmp/ansible-automation-platform-setup-2.4-2/`

```console (error)

```

# STEPS TO REPRODUCE

Sample variable file that was used to call `infra.aap_utilities.aap_setup_download` role
```
aap_setup_down_offline_token: "xxxxeyJhbGciOixxxx"
aap_setup_down_version: "2.4"
aap_setup_down_type: "setup"
aap_setup_rhel_version: "9"
aap_setup_prep_inv_nodes:
  automationcontroller:
    - controller.example.com
aap_setup_prep_inv_vars:
  automationcontroller: # denotes the automation controller nodes as hybrid nodes (controller and execution)
    node_type: hybrid
    ignore_preflight_errors: true
  all:
    pg_database: "awx"
    pg_username: "awx"
    pg_sslmode: "prefer"  # set to 'verify-full' for client-side enforced SSL
    registry_url: "registry.redhat.io"
    receptor_listener_port: 27199
aap_setup_prep_inv_secrets:
  all:
    registry_username: "myregistry_user"
    registry_password: "changeme"
    admin_password: "changeme"
    pg_password: "changeme"
controller_validate_certs: false
```

This caused the the `infra.aap_utilities.aap_setup_install` role to fail with the following error

```
TASK [infra.aap_utilities.aap_setup_install : Run the Ansible Automation Platform setup program] ***
task path: /root/.ansible/collections/ansible_collections/infra/aap_utilities/roles/aap_setup_install/tasks/main.yml:72
ASYNC FAILED on controller: jid=439834133810.20100
fatal: [controller]: FAILED! => {"ansible_job_id": "439834133810.20100", "changed": false, "cmd": "./setup.sh -i inventory", "finished": 1, "msg": "[Errno 2] No such file or directory: b'./setup.sh'", "rc": 2, "results_file": "/root/.ansible_async/439834133810.20100", "started": 1, "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
```

[minimum complete verifiable example]: http://stackoverflow.com/help/mcve

### PR DESCRIPTION
**Pull request by snagoor**
# What does this PR do?

Incorrect setup bundle is downloaded with 2.4 and RHEL9 version `ansible-automation-platform-containerized-setup`

# How should this be tested?

Detailed bug report is provided here https://github.com/redhat-cop/aap_utilities/issues/199

# Is there a relevant Issue open for this?

Provide a link to any open issues that describe the problem you are solving.
resolves #199 

# Other Relevant info, PRs, etc

Please provide link to other PRs that may be related (blocking, resolves, etc. etc.)

### CODE REVIEW

**Review by kubealex — CHANGES_REQUESTED** [review]
To make it future-proof, it could be worth making the check more robust ensuring that the whole package name reflects the required "ansible-automation-platform-setup-bundle" or "ansible-automation-platform-setup" pattern.
By doing this you can safely assume that you are always picking the 'supported' installer bundle.

**Comment by snagoor** [comment]
Thank you for the review. Updated the logic to check `ansible-automation-platform-setup` in file name.

**Comment by jinalklaulitz** [comment]
Could also please remove or increase the elements on the list slice for `__aap_setup_down_images` in line 34; at the loop statement for `name: Downloading the latest installer of type {{ aap_setup_down_type }}`? I'm working with the setup bundle and it was being filtered out since it has more elements now due to the list now including the setup and setup bundle for the containerized setup.

**Review by kubealex — APPROVED** [review]

**Comment by snagoor** [comment]
see also PR #207  which should fix both #199 and #206

**Review by djdanielsson — APPROVED** [review]
I am not positive the addition is required with the other change but I guess it doesn't hurt either.

**Pull request merged**
