### PR TITLE
Add block and task to revoke Openshift token in aap_ocp_install role

### PR DESCRIPTION
**Pull request by rev3r4nt**
# What does this PR do?

In `aap_ocp_install` role, added a block and a task to revoke Openshift API token.

# Other Relevant info, PRs, etc

⚠️  There's a open PR in community.okd (openshift/community.okd/pull/194) to fix intermittent failures when deleting tokens.

### CODE REVIEW

**Review by branic — APPROVED** [review]
LGTM

**Comment by branic** [comment]
@rev3r4nt Thanks for the PR. This is a good addition.

**Comment by branic** [comment]
Pre-commit is failing, please address the failure and then once the CI passes I'll merge.

**Comment by rev3r4nt** [comment]
Thanks @branic it's corrected 👌🏼

**Pull request merged**
